name: Build Qv2ray deps for Windows

on:
  push:
  schedule:
      - cron: '0 0 */2 * *'
      
jobs:
  build:
    strategy:
      matrix:
        arch: [x86-windows, x64-windows]
        package: [grpc, pcre2, libsodium, libiconv]
      fail-fast: false
      
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Update vcpkg
      shell: bash
      run: vcpkg update
    
    - name: Update vcpkg - git
      shell: bash
      run: |
        set +e
        cd $VCPKG_INSTALLATION_ROOT
        git pull --verbose
      
    - name: Install version ${{ matrix.package }} ${{ matrix.arch }}
      run: vcpkg install ${{ matrix.package }}:${{ matrix.arch }}
      
    - name: Export installed libraries
      shell: bash
      run: |
        vcpkg export ${{ matrix.package }}:${{ matrix.arch }} --output=${{ matrix.arch }} --7zip
        cp $VCPKG_INSTALLATION_ROOT/${{ matrix.arch }}.7z ./
        
    - name: Uploading artifact
      uses: actions/upload-artifact@master
      with:
        name: artifacts-${{ matrix.package }}-${{ matrix.arch }}.zip
        path: ${{ matrix.arch }}.7z
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.arch }}.7z
        asset_name: Qv2ray-deps-${{ matrix.package }}-${{ matrix.arch }}.7z
        tag: release
        overwrite: true
